# Autogenerated by devscripts/update-version.py

__version__ = '2023.05.04.120737'

RELEASE_GIT_HEAD = '8f40a10fb25be480860bd61fba39fbdb8612f5b2'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
